# Generated by Django 3.2.4 on 2021-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Город'),
        ),
    ]
