# Generated by Django 3.2.4 on 2021-11-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_shopuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='city',
        ),
    ]
